# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'ubuntu/jammy64'

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder '../', '/backup.git'

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider :virtualbox do |vb|
     # Don't boot with headless mode
     #vb.gui = true
     vb.cpus = 4
     vb.memory = 4096
  
     # Use VBoxManage to customize the VM. For example to change memory:
    # vb.customize ["modifyvm", :id, "--memory", "1024"]
   end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  config.vm.provision "shell", inline: <<END
    apt-get update
    
    # Based off of the Ruby 2.4.10 Dockerfile from commit a564feaaee4c8647c299ab11d41498468bb9af7b of the https://github.com/docker-library/ruby repo, then revised to use rbenv
    apt-get install -y --no-install-recommends \
            bzip2 \
            ca-certificates \
            libffi-dev \
            libgmp-dev \
            libssl-dev \
            libyaml-dev \
            procps \
            zlib1g-dev \
            autoconf \
            bison \
            dpkg-dev \
            gcc \
            libbz2-dev \
            libgdbm-dev \
            libglib2.0-dev \
            libncurses-dev \
            libreadline-dev \
            libxml2-dev \
            libxslt-dev \
            make \
            wget \
            xz-utils \
            curl

    # install additional packages required by dependent gems
    apt-get install -y  g++ \
                        libxml2-dev \
                        libcurl4-openssl-dev

    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | sudo -u vagrant bash
    echo 'eval "$(/home/vagrant/.rbenv/bin/rbenv init - bash)"' >> ~vagrant/.bashrc

    su --login vagrant -c 'eval "$(/home/vagrant/.rbenv/bin/rbenv init - bash)" && 
                               cd /backup.git &&
                               rbenv install &&
                               /home/vagrant/.rbenv/shims/gem install bundler -v 2.3.26'
END
end
